### ISSUE TITLE
Moderation Tool not working as intended? 

### ISSUE THREAD

**Issue by LibertyCitys** [zapprr/republic-core#3]
Moderation tool such as Reports do not have a way to be viewed and if it exists its currently broken.

**Comment by zapprr** [comment]
Currently staff permissions for things are handled via the discord_perms plugin - anyone who has a role that's configured in the plugin as being "Staff" should see reports while in game. I'll need to figure out how exactly it works and document it properly because I haven't touched that code in years.

Reports can also be posted via a Discord webhook - main-sv.lua will have configuration options for that. Those need to be moved into a config file at some point, but for now, you can add webhooks in there.
